---
language: node_js
node_js:
  - 6

cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: '7f6bea7f2fb6d62523003be7259a1bbcd4508fc5'
  on:
    branch: master
after_success:
    - coveralls
notifications:
   slack: opiskelijadash:2M95H1Hl03iTaxd7yav9c5Il