---
language: node_js
node_js:
  - 6

cache:
  directories:
    - "node_modules"

after_success:
    - coveralls
    - "npm run deploy"
notifications:
   slack: opiskelijadash:2M95H1Hl03iTaxd7yav9c5Il