language: node_js
node_js:
  - "node"
before_deploy: 
# npm run predeploy builds to /build/ folder
  - npm run predeploy
# GH-pages only understand to show /dist/ folder's webpages, so rename /build to /dist
  - mv ./build ./dist
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master