language: node_js
node_js:
  - "node"
before_deploy:
# npm run predeploy builds to /build/ folder
  - npm run predeploy
# GH-pages only understand to show /dist/ folder's webpages, so rename /build to /dist
  - mv ./build ./dist
  - cp ./dist/js/main.*.js mainDash.js
  - cp ./dist/css/main.*.css mainDash.css
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
