---
language: node_js
node_js:
  - 6

cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
after_success:
    - coveralls
    - "npm run deploy"
notifications:
   slack: opiskelijadash:2M95H1Hl03iTaxd7yav9c5Il