language: node_js
node_js:
  - "node"
before_deploy:
# npm run predeploy builds to /build/ folder
  - npm run predeploy
# GH-pages only understand to show web-content from the root index.html, so splash build to there
  - mv ./build/* .
  - rm -r ./build
# Duplicate js & css files with dynamic names to static mainDash.js/css for ohpe2017-material's link-usage
  - cp ./static/js/main.*.js dashboard/static/js/mainDash.js
  - cp ./static/css/main.*.css dashboard/static/css/mainDash.css
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
